name: Tests for the development branch

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

permissions: read-all

jobs:
  test_dev:
    name: Tests for the development
    runs-on: ubuntu-22.04

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a '${{ github.event_name }}' event."
      - run: echo "ğŸ§ This job is now running on a '${{ runner.os }}' server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is '${{ github.ref }}' and your repository is '${{ github.repository }}'."

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The '${{ github.repository }}' repository has been cloned to the runner."

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - run: python --version

      - name: Instal packages
        run: |
          pip install pytest
          pytest --version

      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: Run tests with pytest
        run: pytest

      - run: echo "ğŸ This job's status is '${{ job.status }}'."
